//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Web.DespachoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Despacho", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Mant.Dominio")]
    [System.SerializableAttribute()]
    public partial class Despacho : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_despachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_tipo_estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_compra {
            get {
                return this.id_compraField;
            }
            set {
                if ((this.id_compraField.Equals(value) != true)) {
                    this.id_compraField = value;
                    this.RaisePropertyChanged("id_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_despacho {
            get {
                return this.id_despachoField;
            }
            set {
                if ((this.id_despachoField.Equals(value) != true)) {
                    this.id_despachoField = value;
                    this.RaisePropertyChanged("id_despacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_tipo_estado {
            get {
                return this.id_tipo_estadoField;
            }
            set {
                if ((this.id_tipo_estadoField.Equals(value) != true)) {
                    this.id_tipo_estadoField = value;
                    this.RaisePropertyChanged("id_tipo_estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Mant.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DespachoWS.IServiceDespacho")]
    public interface IServiceDespacho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDespacho/CrearDespacho", ReplyAction="http://tempuri.org/IServiceDespacho/CrearDespachoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Front_Web.DespachoWS.RepetidoException), Action="http://tempuri.org/IServiceDespacho/CrearDespachoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Mant.Errores")]
        Front_Web.DespachoWS.Despacho CrearDespacho(Front_Web.DespachoWS.Despacho DespachoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDespacho/CrearDespacho", ReplyAction="http://tempuri.org/IServiceDespacho/CrearDespachoResponse")]
        System.Threading.Tasks.Task<Front_Web.DespachoWS.Despacho> CrearDespachoAsync(Front_Web.DespachoWS.Despacho DespachoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDespacho/ObtenerDespacho", ReplyAction="http://tempuri.org/IServiceDespacho/ObtenerDespachoResponse")]
        Front_Web.DespachoWS.Despacho ObtenerDespacho(int id_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDespacho/ObtenerDespacho", ReplyAction="http://tempuri.org/IServiceDespacho/ObtenerDespachoResponse")]
        System.Threading.Tasks.Task<Front_Web.DespachoWS.Despacho> ObtenerDespachoAsync(int id_compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDespacho/ListarDespachos", ReplyAction="http://tempuri.org/IServiceDespacho/ListarDespachosResponse")]
        Front_Web.DespachoWS.Despacho[] ListarDespachos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDespacho/ListarDespachos", ReplyAction="http://tempuri.org/IServiceDespacho/ListarDespachosResponse")]
        System.Threading.Tasks.Task<Front_Web.DespachoWS.Despacho[]> ListarDespachosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDespachoChannel : Front_Web.DespachoWS.IServiceDespacho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDespachoClient : System.ServiceModel.ClientBase<Front_Web.DespachoWS.IServiceDespacho>, Front_Web.DespachoWS.IServiceDespacho {
        
        public ServiceDespachoClient() {
        }
        
        public ServiceDespachoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDespachoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDespachoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDespachoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Front_Web.DespachoWS.Despacho CrearDespacho(Front_Web.DespachoWS.Despacho DespachoACrear) {
            return base.Channel.CrearDespacho(DespachoACrear);
        }
        
        public System.Threading.Tasks.Task<Front_Web.DespachoWS.Despacho> CrearDespachoAsync(Front_Web.DespachoWS.Despacho DespachoACrear) {
            return base.Channel.CrearDespachoAsync(DespachoACrear);
        }
        
        public Front_Web.DespachoWS.Despacho ObtenerDespacho(int id_compra) {
            return base.Channel.ObtenerDespacho(id_compra);
        }
        
        public System.Threading.Tasks.Task<Front_Web.DespachoWS.Despacho> ObtenerDespachoAsync(int id_compra) {
            return base.Channel.ObtenerDespachoAsync(id_compra);
        }
        
        public Front_Web.DespachoWS.Despacho[] ListarDespachos() {
            return base.Channel.ListarDespachos();
        }
        
        public System.Threading.Tasks.Task<Front_Web.DespachoWS.Despacho[]> ListarDespachosAsync() {
            return base.Channel.ListarDespachosAsync();
        }
    }
}
