//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Web.WSArticulos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articulo", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Mant.Dominio")]
    [System.SerializableAttribute()]
    public partial class Articulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descArticuloField;
        
        private bool estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUnidadMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descArticulo {
            get {
                return this.descArticuloField;
            }
            set {
                if ((object.ReferenceEquals(this.descArticuloField, value) != true)) {
                    this.descArticuloField = value;
                    this.RaisePropertyChanged("descArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                if ((this.idArticuloField.Equals(value) != true)) {
                    this.idArticuloField = value;
                    this.RaisePropertyChanged("idArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUnidadMedida {
            get {
                return this.idUnidadMedidaField;
            }
            set {
                if ((this.idUnidadMedidaField.Equals(value) != true)) {
                    this.idUnidadMedidaField = value;
                    this.RaisePropertyChanged("idUnidadMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSArticulos.IServiceArticulo")]
    public interface IServiceArticulo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/CrearArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/CrearArticuloResponse")]
        Front_Web.WSArticulos.Articulo CrearArticulo(Front_Web.WSArticulos.Articulo articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/CrearArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/CrearArticuloResponse")]
        System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo> CrearArticuloAsync(Front_Web.WSArticulos.Articulo articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/ObtenerArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/ObtenerArticuloResponse")]
        Front_Web.WSArticulos.Articulo ObtenerArticulo(int IdArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/ObtenerArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/ObtenerArticuloResponse")]
        System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo> ObtenerArticuloAsync(int IdArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/ModificarArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/ModificarArticuloResponse")]
        Front_Web.WSArticulos.Articulo ModificarArticulo(Front_Web.WSArticulos.Articulo articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/ModificarArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/ModificarArticuloResponse")]
        System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo> ModificarArticuloAsync(Front_Web.WSArticulos.Articulo articulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/EliminarArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/EliminarArticuloResponse")]
        void EliminarArticulo(int IdArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/EliminarArticulo", ReplyAction="http://tempuri.org/IServiceArticulo/EliminarArticuloResponse")]
        System.Threading.Tasks.Task EliminarArticuloAsync(int IdArticulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/ListaArticulos", ReplyAction="http://tempuri.org/IServiceArticulo/ListaArticulosResponse")]
        Front_Web.WSArticulos.Articulo[] ListaArticulos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticulo/ListaArticulos", ReplyAction="http://tempuri.org/IServiceArticulo/ListaArticulosResponse")]
        System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo[]> ListaArticulosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceArticuloChannel : Front_Web.WSArticulos.IServiceArticulo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceArticuloClient : System.ServiceModel.ClientBase<Front_Web.WSArticulos.IServiceArticulo>, Front_Web.WSArticulos.IServiceArticulo {
        
        public ServiceArticuloClient() {
        }
        
        public ServiceArticuloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceArticuloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArticuloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArticuloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Front_Web.WSArticulos.Articulo CrearArticulo(Front_Web.WSArticulos.Articulo articulo) {
            return base.Channel.CrearArticulo(articulo);
        }
        
        public System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo> CrearArticuloAsync(Front_Web.WSArticulos.Articulo articulo) {
            return base.Channel.CrearArticuloAsync(articulo);
        }
        
        public Front_Web.WSArticulos.Articulo ObtenerArticulo(int IdArticulo) {
            return base.Channel.ObtenerArticulo(IdArticulo);
        }
        
        public System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo> ObtenerArticuloAsync(int IdArticulo) {
            return base.Channel.ObtenerArticuloAsync(IdArticulo);
        }
        
        public Front_Web.WSArticulos.Articulo ModificarArticulo(Front_Web.WSArticulos.Articulo articulo) {
            return base.Channel.ModificarArticulo(articulo);
        }
        
        public System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo> ModificarArticuloAsync(Front_Web.WSArticulos.Articulo articulo) {
            return base.Channel.ModificarArticuloAsync(articulo);
        }
        
        public void EliminarArticulo(int IdArticulo) {
            base.Channel.EliminarArticulo(IdArticulo);
        }
        
        public System.Threading.Tasks.Task EliminarArticuloAsync(int IdArticulo) {
            return base.Channel.EliminarArticuloAsync(IdArticulo);
        }
        
        public Front_Web.WSArticulos.Articulo[] ListaArticulos() {
            return base.Channel.ListaArticulos();
        }
        
        public System.Threading.Tasks.Task<Front_Web.WSArticulos.Articulo[]> ListaArticulosAsync() {
            return base.Channel.ListaArticulosAsync();
        }
    }
}
