//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Web.ComprasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Mant.Dominio")]
    [System.SerializableAttribute()]
    public partial class Compra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumaTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DescuentoTotal {
            get {
                return this.DescuentoTotalField;
            }
            set {
                if ((this.DescuentoTotalField.Equals(value) != true)) {
                    this.DescuentoTotalField = value;
                    this.RaisePropertyChanged("DescuentoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega {
            get {
                return this.FechaEntregaField;
            }
            set {
                if ((this.FechaEntregaField.Equals(value) != true)) {
                    this.FechaEntregaField = value;
                    this.RaisePropertyChanged("FechaEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompra {
            get {
                return this.IdCompraField;
            }
            set {
                if ((this.IdCompraField.Equals(value) != true)) {
                    this.IdCompraField = value;
                    this.RaisePropertyChanged("IdCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoEntrega {
            get {
                return this.IdTipoEntregaField;
            }
            set {
                if ((this.IdTipoEntregaField.Equals(value) != true)) {
                    this.IdTipoEntregaField = value;
                    this.RaisePropertyChanged("IdTipoEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoEstado {
            get {
                return this.IdTipoEstadoField;
            }
            set {
                if ((this.IdTipoEstadoField.Equals(value) != true)) {
                    this.IdTipoEstadoField = value;
                    this.RaisePropertyChanged("IdTipoEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SumaTotal {
            get {
                return this.SumaTotalField;
            }
            set {
                if ((this.SumaTotalField.Equals(value) != true)) {
                    this.SumaTotalField = value;
                    this.RaisePropertyChanged("SumaTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComprasWS.IServiceCompra")]
    public interface IServiceCompra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompra/ListarCompra", ReplyAction="http://tempuri.org/IServiceCompra/ListarCompraResponse")]
        Front_Web.ComprasWS.Compra[] ListarCompra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompra/ListarCompra", ReplyAction="http://tempuri.org/IServiceCompra/ListarCompraResponse")]
        System.Threading.Tasks.Task<Front_Web.ComprasWS.Compra[]> ListarCompraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompra/ModificarCompra", ReplyAction="http://tempuri.org/IServiceCompra/ModificarCompraResponse")]
        Front_Web.ComprasWS.Compra ModificarCompra([System.ServiceModel.MessageParameterAttribute(Name="ModificarCompra")] Front_Web.ComprasWS.Compra ModificarCompra1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompra/ModificarCompra", ReplyAction="http://tempuri.org/IServiceCompra/ModificarCompraResponse")]
        System.Threading.Tasks.Task<Front_Web.ComprasWS.Compra> ModificarCompraAsync(Front_Web.ComprasWS.Compra ModificarCompra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCompraChannel : Front_Web.ComprasWS.IServiceCompra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCompraClient : System.ServiceModel.ClientBase<Front_Web.ComprasWS.IServiceCompra>, Front_Web.ComprasWS.IServiceCompra {
        
        public ServiceCompraClient() {
        }
        
        public ServiceCompraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCompraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCompraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCompraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Front_Web.ComprasWS.Compra[] ListarCompra() {
            return base.Channel.ListarCompra();
        }
        
        public System.Threading.Tasks.Task<Front_Web.ComprasWS.Compra[]> ListarCompraAsync() {
            return base.Channel.ListarCompraAsync();
        }
        
        public Front_Web.ComprasWS.Compra ModificarCompra(Front_Web.ComprasWS.Compra ModificarCompra1) {
            return base.Channel.ModificarCompra(ModificarCompra1);
        }
        
        public System.Threading.Tasks.Task<Front_Web.ComprasWS.Compra> ModificarCompraAsync(Front_Web.ComprasWS.Compra ModificarCompra) {
            return base.Channel.ModificarCompraAsync(ModificarCompra);
        }
    }
}
