//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_Web.ComprasDetalleWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraD", Namespace="http://schemas.datacontract.org/2004/07/Servicio_Mant.Dominio")]
    [System.SerializableAttribute()]
    public partial class CompraD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdArticuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCompraDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdArticulo {
            get {
                return this.IdArticuloField;
            }
            set {
                if ((this.IdArticuloField.Equals(value) != true)) {
                    this.IdArticuloField = value;
                    this.RaisePropertyChanged("IdArticulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompra {
            get {
                return this.IdCompraField;
            }
            set {
                if ((this.IdCompraField.Equals(value) != true)) {
                    this.IdCompraField = value;
                    this.RaisePropertyChanged("IdCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCompraD {
            get {
                return this.IdCompraDField;
            }
            set {
                if ((this.IdCompraDField.Equals(value) != true)) {
                    this.IdCompraDField = value;
                    this.RaisePropertyChanged("IdCompraD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ComprasDetalleWS.IServiceCompraD")]
    public interface IServiceCompraD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/CrearCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/CrearCompraDResponse")]
        Front_Web.ComprasDetalleWS.CompraD CrearCompraD(Front_Web.ComprasDetalleWS.CompraD compraDACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/CrearCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/CrearCompraDResponse")]
        System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD> CrearCompraDAsync(Front_Web.ComprasDetalleWS.CompraD compraDACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/ObtenerCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/ObtenerCompraDResponse")]
        Front_Web.ComprasDetalleWS.CompraD ObtenerCompraD(int idcomprad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/ObtenerCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/ObtenerCompraDResponse")]
        System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD> ObtenerCompraDAsync(int idcomprad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/ModificarCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/ModificarCompraDResponse")]
        Front_Web.ComprasDetalleWS.CompraD ModificarCompraD(Front_Web.ComprasDetalleWS.CompraD compraDAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/ModificarCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/ModificarCompraDResponse")]
        System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD> ModificarCompraDAsync(Front_Web.ComprasDetalleWS.CompraD compraDAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/EliminarCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/EliminarCompraDResponse")]
        void EliminarCompraD(int idcomprad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/EliminarCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/EliminarCompraDResponse")]
        System.Threading.Tasks.Task EliminarCompraDAsync(int idcomprad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/ListarCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/ListarCompraDResponse")]
        Front_Web.ComprasDetalleWS.CompraD[] ListarCompraD(int idcompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCompraD/ListarCompraD", ReplyAction="http://tempuri.org/IServiceCompraD/ListarCompraDResponse")]
        System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD[]> ListarCompraDAsync(int idcompra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCompraDChannel : Front_Web.ComprasDetalleWS.IServiceCompraD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCompraDClient : System.ServiceModel.ClientBase<Front_Web.ComprasDetalleWS.IServiceCompraD>, Front_Web.ComprasDetalleWS.IServiceCompraD {
        
        public ServiceCompraDClient() {
        }
        
        public ServiceCompraDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCompraDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCompraDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCompraDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Front_Web.ComprasDetalleWS.CompraD CrearCompraD(Front_Web.ComprasDetalleWS.CompraD compraDACrear) {
            return base.Channel.CrearCompraD(compraDACrear);
        }
        
        public System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD> CrearCompraDAsync(Front_Web.ComprasDetalleWS.CompraD compraDACrear) {
            return base.Channel.CrearCompraDAsync(compraDACrear);
        }
        
        public Front_Web.ComprasDetalleWS.CompraD ObtenerCompraD(int idcomprad) {
            return base.Channel.ObtenerCompraD(idcomprad);
        }
        
        public System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD> ObtenerCompraDAsync(int idcomprad) {
            return base.Channel.ObtenerCompraDAsync(idcomprad);
        }
        
        public Front_Web.ComprasDetalleWS.CompraD ModificarCompraD(Front_Web.ComprasDetalleWS.CompraD compraDAModificar) {
            return base.Channel.ModificarCompraD(compraDAModificar);
        }
        
        public System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD> ModificarCompraDAsync(Front_Web.ComprasDetalleWS.CompraD compraDAModificar) {
            return base.Channel.ModificarCompraDAsync(compraDAModificar);
        }
        
        public void EliminarCompraD(int idcomprad) {
            base.Channel.EliminarCompraD(idcomprad);
        }
        
        public System.Threading.Tasks.Task EliminarCompraDAsync(int idcomprad) {
            return base.Channel.EliminarCompraDAsync(idcomprad);
        }
        
        public Front_Web.ComprasDetalleWS.CompraD[] ListarCompraD(int idcompra) {
            return base.Channel.ListarCompraD(idcompra);
        }
        
        public System.Threading.Tasks.Task<Front_Web.ComprasDetalleWS.CompraD[]> ListarCompraDAsync(int idcompra) {
            return base.Channel.ListarCompraDAsync(idcompra);
        }
    }
}
